### PR TITLE
[New Model] PoET

### PR DESCRIPTION
**Pull request by timt51**
This PR adds a new baseline model, [PoET](https://papers.nips.cc/paper_files/paper/2023/hash/f4366126eba252699b280e8f93c0ab2f-Abstract-Conference.html), for the following benchmarks: `DMS substitutions`, `DMS indels`, `clinical substitutions`, and `clinical indels`.

1. To download the model, MSAs used by the model to make predictions for the benchmarks, and model score files containing predictions for the benchmarks, run the following commands:

```
cd proteingym/baselines/PoET
make download DOWNLOAD_DIR=<your-download-directory>
```

This command will create the following files and directories in the specified download directory:

```
poet.ckpt
  - the model checkpoint
msas/DMS_substitutions
  - directory containing MSAs for DMS substitutions benchmark, one file per dataset
msas/DMS_indels
  - directory containing MSAs for DMS indels benchmark, one file per dataset
msas/clinical_substitutions
  - directory containing MSAs for clinical substitutions benchmark, one file per dataset
msas/clinical_indels
  - directory containing MSAs for clinical indels benchmark, one file per dataset
zero_shot_DMS_substitutions_scores/PoET
  - directory containing model scores for DMS substitutions benchmark, one file per dataset
zero_shot_DMS_indels_scores/PoET
  - directory containing model scores for DMS indels benchmark, one file per dataset
zero_shot_clinical_substitutions_scores/PoET
  - directory containing model scores for clinical substitutions benchmark, one file per dataset
zero_shot_clinical_indels_scores/PoET
  - directory containing model scores for clinical indels benchmark, one file per dataset
LICENSE
  - license for model weights
```

2. To create the conda environment required to run the inference code, run:

```
cd proteingym/baselines/PoET
make create_conda_env
```

This will create a conda environment named `poet`.

3. Using the provided scripts for computing model performance on the DMS benchmarks, I obtained an average Spearman correlation of `0.474` for the DMS substitutions benchmark and `0.519` for the DMS indels benchmark.

4. For the clinical benchmarks, I calculated an average AUROC of `0.924` for the clinical substitutions benchmark and a global AUROC of `0.941` for the clinical indels benchmark.

5. For the clinical benchmarks, we found that a longer context length consistently outperforms shorter context lengths. Thus, diverging from the hyperparameters used in the original paper, we used a longer context length of `49152` tokens when scoring sequences in the clinical benchmarks. For the DMS benchmarks, we continue to ensemble over a range of context lengths (`6144`, `12288`, and `24576`) as described in the original paper. The model scoring files for the clinical benchmarks also contain the scores of PoET at context lengths `6144`, `12288`, and `24576`, provided for convenience if others want to analyze this data.

### CODE REVIEW

**Comment by pascalnotin** [comment]
Hi @timt51 -- thank you for the PR, and apologies about the delay getting back to you about it! 

The code was in great shape (thanks for that!), and is now ready to merge into main after a few tweaks on our side. 

However, we are getting slightly different performance results vs the one you are reporting above (we have done two independent full reproductions). For instance, for the zero-shot DMS substitutions benchmark we obtain an avg Spearman performance of 0.47 twice (instead of 0.474) and for the zero-shot DMS indels benchmark we get 0.517 twice (vs 0.519). 
Looking at the per-DMS performance, our two reproductions get basically the same performance across all assays, but they are noticeably different than the ones in your PR (sometimes higher, sometimes lower).

We use the same hypers as in the PoET scoring script you provided, and use the MSAs included in your PR. Would you know what could explain the discrepancy?

**Comment by pascalnotin** [comment]
I have merged your PR into main in the meantime. Will update performance files once we have reconciled the score discrepancies.

**Comment by timt51** [comment]
Hi @pascalnotin, thanks for including yet another model in ProteinGym! Glad to hear the code was easy to work with.

The results in your reproductions seem close enough to be within the margin of error, so they should be valid. I think the differences are most likely due to

- minor code differences. The results I shared were obtained by merging our results from the original ProteinGymV0.1 with results we calculated later for the remaining datasets in ProteinGymV1. There were some changes to the code in between. Most changes were purely cosmetic or trivial changes to improve algorithm efficiency, although one minor but not completely trivial change is that we're now calculating the MSA sampling weights before applying the sequence similarity filter instead of after; this allows the sampling weight calculations to be more easily reused between different sequence similarity filter thresholds.
- source of non-determinism that isn't being controlled for in the code
- differences in seeds between our runs
- differences in deterministic operations between different hardware or simply non-determinism induced by the hardware (this tends to have a bigger effect when using lower floating point precision like we are here)

(When I said "Using the provided scripts for computing model performance on the DMS benchmarks", I meant that I used the provided scripts for computing the summary statistics only)

**Comment by pascalnotin** [comment]
Hi @timt51 - thank you for confirming, makes sense! Just pushed the DMS results to the repo a few minutes ago. Will kick off the clinical scoring and update once ready. Congrats again on a very nice paper!

**Pull request merged**
